### ISSUE TITLE
clean up art directories

### ISSUE THREAD

**Issue by quinkennedy** [quinkennedy/bitbitJAM3#1]
I would like to pare down what is in the art directory. I propose removing all assets that are not being used in the game. If you want to keep things like the ship that were used for some prototypes, we can move those to the prototype directory.

I would also like to remove all generated files (.ase, .txt). I have been having problems with using the .gif files (first frame exports with black background instead of transparent. I assume it is an issue with my tools), so I propose keeping only .psd and .png files.

**Comment by davidfrankel** [comment]
Cool, no problem.  Take a look at my last couple commits, see if that works for you.  I had been using the art folder as a hybrid artist workspace and art-to-engineering transfer space, so I can see how that probably was confusing.  (btw .ase aren't generated, they're source files -- similar to psd)

**Comment by quinkennedy** [comment]
Oh, I thought the .ase files were another form of the .txt files, if they
are source files, it's totally fine to keep them in the repo
